const HotelActions = {
  CREATE_HOTEL:"CREATE_HOTEL",
  CREATE_HOTEL_SUCCESS: "CREATE_HOTEL_SUCCESS",
  FETCH_FAVORITE_HOTELS: "FETCH_FAVORITE_HOTELS",
  FETCH_FAVORITE_HOTELS_SUCCESS: "FETCH_FAVORITE_HOTELS_SUCCESS",

  FETCH_ALL_HOTEL: "FETCH_ALL_HOTEL",
  FETCH_All_HOTEL_SUCCESS: " FETCH_All_HOTEL_SUCCESS",

  FETCH_TOP3_HOTEL: "FETCH_TOP3_HOTEL",
  FETCH_TOP3_HOTEL_SUCCESS: "FETCH_TOP3_HOTEL_SUCCESS",
  
  FETCH_OWNER_HOTEL:"FETCH_OWNER_HOTEL",
  FETCH_OWNER_HOTEL_SUCCESS:"FETCH_OWNER_HOTEL_SUCCESS",
  UPDATE_HOTEL: "UPDATE_HOTEL",
  UPDATE_HOTEL_SUCCESS: "UPDATE_HOTEL_SUCCESS",
  UPDATE_HOTEL_SERVICE_STATUS: "UPDATE_HOTEL_SERVICE_STATUS",
  UPDATE_HOTEL_SERVICE_STATUS_SUCCESS: "UPDATE_HOTEL_SERVICE_STATUS_SUCCESS",  
  CREATE_HOTEL_SERVICE: "CREATE_HOTEL_SERVICE",
  CREATE_HOTEL_SERVICE_SUCCESS: "CREATE_HOTEL_SERVICE_SUCCESS",

  SAVE_HOTEL_NAME_CREATE: "SAVE_HOTEL_NAME_CREATE", 
  SAVE_HOTEL_ADDRESS_CREATE: "SAVE_HOTEL_ADDRESS_CREATE",
  SAVE_HOTEL_FACILITIES_CREATE: "SAVE_HOTEL_FACILITIES_CREATE",
  SAVE_HOTEL_CHECKTIME_CREATE: "SAVE_HOTEL_CHECKTIME_CREATE",
  SAVE_HOTEL_DESCRIPTION_CREATE: "SAVE_HOTEL_DESCRIPTION_CREATE",
  EDIT_HOTEL_DESCRIPTION_CREATE: "EDIT_HOTEL_DESCRIPTION_CREATE",

  ROOM_CREATE: "ROOM_CREATE"
};
export default HotelActions;
