const ReservationActions = {
  FETCH_RESERVATIONS: "FETCH_RESERVATIONS",
  FETCH_RESERVATIONS_SUCCESS: "FETCH_RESERVATIONS_SUCCESS",
  FETCH_RESERVATIONS_FAILURE: "FETCH_RESERVATIONS_FAILURE",
};

export default ReservationActions;
