import {
  FaWifi,
  FaSwimmingPool,
  FaParking,
  FaConciergeBell,
  FaUtensils,
  FaDumbbell,
  FaShuttleVan,
  FaSpa,
  FaChalkboardTeacher,
  FaDog,
  FaWineBottle,
  FaHandsWash,
} from "react-icons/fa";

export const cityOptionSelect = [
  { value: "Hà Nội", label: "Hà Nội" },
  { value: "Hồ Chí Minh", label: "Hồ Chí Minh" },
  { value: "Đà Nẵng", label: "Đà Nẵng" },
  { value: "Hải Phòng", label: "Hải Phòng" },
  { value: "Cần Thơ", label: "Cần Thơ" },
  { value: "An Giang", label: "An Giang" },
  { value: "Bà Rịa - Vũng Tàu", label: "Bà Rịa - Vũng Tàu" },
  { value: "Bắc Giang", label: "Bắc Giang" },
  { value: "Bắc Kạn", label: "Bắc Kạn" },
  { value: "Bạc Liêu", label: "Bạc Liêu" },
  { value: "Bắc Ninh", label: "Bắc Ninh" },
  { value: "Bến Tre", label: "Bến Tre" },
  { value: "Bình Định", label: "Bình Định" },
  { value: "Bình Dương", label: "Bình Dương" },
  { value: "Bình Phước", label: "Bình Phước" },
  { value: "Bình Thuận", label: "Bình Thuận" },
  { value: "Cà Mau", label: "Cà Mau" },
  { value: "Cao Bằng", label: "Cao Bằng" },
  { value: "Đắk Lắk", label: "Đắk Lắk" },
  { value: "Đắk Nông", label: "Đắk Nông" },
  { value: "Điện Biên", label: "Điện Biên" },
  { value: "Đồng Nai", label: "Đồng Nai" },
  { value: "Đồng Tháp", label: "Đồng Tháp" },
  { value: "Gia Lai", label: "Gia Lai" },
  { value: "Hà Giang", label: "Hà Giang" },
  { value: "Hà Nam", label: "Hà Nam" },
  { value: "Hà Tĩnh", label: "Hà Tĩnh" },
  { value: "Hải Dương", label: "Hải Dương" },
  { value: "Hậu Giang", label: "Hậu Giang" },
  { value: "Hòa Bình", label: "Hòa Bình" },
  { value: "Hưng Yên", label: "Hưng Yên" },
  { value: "Khánh Hòa", label: "Khánh Hòa" },
  { value: "Kiên Giang", label: "Kiên Giang" },
  { value: "Kon Tum", label: "Kon Tum" },
  { value: "Lai Châu", label: "Lai Châu" },
  { value: "Lâm Đồng", label: "Lâm Đồng" },
  { value: "Lạng Sơn", label: "Lạng Sơn" },
  { value: "Lào Cai", label: "Lào Cai" },
  { value: "Long An", label: "Long An" },
  { value: "Nam Định", label: "Nam Định" },
  { value: "Nghệ An", label: "Nghệ An" },
  { value: "Ninh Bình", label: "Ninh Bình" },
  { value: "Ninh Thuận", label: "Ninh Thuận" },
  { value: "Phú Thọ", label: "Phú Thọ" },
  { value: "Phú Yên", label: "Phú Yên" },
  { value: "Quảng Bình", label: "Quảng Bình" },
  { value: "Quảng Nam", label: "Quảng Nam" },
  { value: "Quảng Ngãi", label: "Quảng Ngãi" },
  { value: "Quảng Ninh", label: "Quảng Ninh" },
  { value: "Quảng Trị", label: "Quảng Trị" },
  { value: "Sóc Trăng", label: "Sóc Trăng" },
  { value: "Sơn La", label: "Sơn La" },
  { value: "Tây Ninh", label: "Tây Ninh" },
  { value: "Thái Bình", label: "Thái Bình" },
  { value: "Thái Nguyên", label: "Thái Nguyên" },
  { value: "Thanh Hóa", label: "Thanh Hóa" },
  { value: "Thừa Thiên Huế", label: "Thừa Thiên Huế" },
  { value: "Tiền Giang", label: "Tiền Giang" },
  { value: "Trà Vinh", label: "Trà Vinh" },
  { value: "Tuyên Quang", label: "Tuyên Quang" },
  { value: "Vĩnh Long", label: "Vĩnh Long" },
  { value: "Vĩnh Phúc", label: "Vĩnh Phúc" },
  { value: "Yên Bái", label: "Yên Bái" },
];

export const districtsByCity = {
  "Đà Nẵng": [
    { value: "Hải Châu", label: "Hải Châu" },
    { value: "Thanh Khê", label: "Thanh Khê" },
    { value: "Sơn Trà", label: "Sơn Trà" },
    { value: "Ngũ Hành Sơn", label: "Ngũ Hành Sơn" },
    { value: "Liên Chiểu", label: "Liên Chiểu" },
    { value: "Cẩm Lệ", label: "Cẩm Lệ" },
    { value: "Hòa Vang", label: "Hòa Vang" },
    { value: "Hoàng Sa", label: "Hoàng Sa" },
  ],
  "Hà Nội": [
    { value: "Ba Đình", label: "Ba Đình" },
    { value: "Hoàn Kiếm", label: "Hoàn Kiếm" },
    { value: "Tây Hồ", label: "Tây Hồ" },
    { value: "Long Biên", label: "Long Biên" },
    { value: "Cầu Giấy", label: "Cầu Giấy" },
    { value: "Đống Đa", label: "Đống Đa" },
    { value: "Hai Bà Trưng", label: "Hai Bà Trưng" },
    { value: "Hoàng Mai", label: "Hoàng Mai" },
    { value: "Thanh Xuân", label: "Thanh Xuân" },
    { value: "Sóc Sơn", label: "Sóc Sơn" },
    { value: "Đông Anh", label: "Đông Anh" },
    { value: "Gia Lâm", label: "Gia Lâm" },
    { value: "Nam Từ Liêm", label: "Nam Từ Liêm" },
    { value: "Bắc Từ Liêm", label: "Bắc Từ Liêm" },
    { value: "Mê Linh", label: "Mê Linh" },
    { value: "Hà Đông", label: "Hà Đông" },
    { value: "Sơn Tây", label: "Sơn Tây" },
    { value: "Ba Vì", label: "Ba Vì" },
    { value: "Phúc Thọ", label: "Phúc Thọ" },
    { value: "Đan Phượng", label: "Đan Phượng" },
    { value: "Hoài Đức", label: "Hoài Đức" },
    { value: "Quốc Oai", label: "Quốc Oai" },
    { value: "Thạch Thất", label: "Thạch Thất" },
    { value: "Chương Mỹ", label: "Chương Mỹ" },
    { value: "Thanh Oai", label: "Thanh Oai" },
    { value: "Thường Tín", label: "Thường Tín" },
    { value: "Phú Xuyên", label: "Phú Xuyên" },
    { value: "Ứng Hòa", label: "Ứng Hòa" },
    { value: "Mỹ Đức", label: "Mỹ Đức" },
  ],
  "Hồ Chí Minh": [
    { value: "Quận 1", label: "Quận 1" },
    { value: "Quận 3", label: "Quận 3" },
    { value: "Quận 4", label: "Quận 4" },
    { value: "Quận 5", label: "Quận 5" },
    { value: "Quận 6", label: "Quận 6" },
    { value: "Quận 7", label: "Quận 7" },
    { value: "Quận 8", label: "Quận 8" },
    { value: "Quận 10", label: "Quận 10" },
    { value: "Quận 11", label: "Quận 11" },
    { value: "Quận 12", label: "Quận 12" },
    { value: "Bình Thạnh", label: "Bình Thạnh" },
    { value: "Tân Bình", label: "Tân Bình" },
    { value: "Tân Phú", label: "Tân Phú" },
    { value: "Phú Nhuận", label: "Phú Nhuận" },
    { value: "Gò Vấp", label: "Gò Vấp" },
    { value: "Bình Tân", label: "Bình Tân" },
    { value: "Thủ Đức", label: "Thủ Đức" },
    { value: "Củ Chi", label: "Củ Chi" },
    { value: "Hóc Môn", label: "Hóc Môn" },
    { value: "Bình Chánh", label: "Bình Chánh" },
    { value: "Nhà Bè", label: "Nhà Bè" },
    { value: "Cần Giờ", label: "Cần Giờ" },
  ],
};

export const listFacilities = [
  {
    name: "Free Wi-Fi",
    icon: "FaWifi",
    description: "Free high-speed internet for guests.",
    iconTemp: FaWifi,
  },
  {
    name: "Swimming Pool",
    icon: "FaSwimmingPool",
    description: "Spacious, clean, and modern swimming pool.",
    iconTemp: FaSwimmingPool,
  },
  {
    name: "Parking Lot",
    icon: "FaParking",
    description: "Free parking available for staying guests.",
    iconTemp: FaParking,
  },
  {
    name: "24/7 Room Service",
    icon: "FaConciergeBell",
    description: "Room service available at all times.",
    iconTemp: FaConciergeBell,
  },
  {
    name: "Restaurant",
    icon: "FaUtensils",
    description: "Restaurant serving a wide variety of delicious dishes.",
    iconTemp: FaUtensils,
  },
  {
    name: "Fitness Center",
    icon: "FaDumbbell",
    description: "Gym fully equipped with modern facilities.",
    iconTemp: FaDumbbell,
  },
  {
    name: "Airport Shuttle",
    icon: "FaShuttleVan",
    description: "Convenient airport transfer service for guests.",
    iconTemp: FaShuttleVan,
  },
  {
    name: "Spa & Wellness Center",
    icon: "FaSpa",
    description: "Relaxing spa treatments and wellness options.",
    iconTemp: FaSpa,
  },
  {
    name: "Laundry Service",
    icon: "FaHandsWash",
    description: "Professional laundry and dry-cleaning service.",
    iconTemp: FaHandsWash,
  },
  {
    name: "Conference Room",
    icon: "FaChalkboardTeacher",
    description: "Spacious and well-equipped conference facilities.",
    iconTemp: FaChalkboardTeacher,
  },
  {
    name: "Pet-Friendly",
    icon: "FaDog",
    description: "Pets are welcome in designated rooms.",
    iconTemp: FaDog,
  },
  {
    name: "Mini Bar",
    icon: "FaWineBottle",
    description: "In-room mini bar with snacks and beverages.",
    iconTemp: FaWineBottle,
  },
];


export const wardsByDistrict = {
  // ===== ĐÀ NẴNG =====
  "Hải Châu": [
    { value: "Hải Châu 1", label: "Hải Châu 1" },
    { value: "Hải Châu 2", label: "Hải Châu 2" },
    { value: "Thạch Thang", label: "Thạch Thang" },
    { value: "Thanh Bình", label: "Thanh Bình" },
    { value: "Thuận Phước", label: "Thuận Phước" },
    { value: "Bình Hiên", label: "Bình Hiên" },
    { value: "Bình Thuận", label: "Bình Thuận" },
    { value: "Hòa Cường Bắc", label: "Hòa Cường Bắc" },
    { value: "Hòa Cường Nam", label: "Hòa Cường Nam" },
    { value: "Hòa Thuận Đông", label: "Hòa Thuận Đông" },
    { value: "Hòa Thuận Tây", label: "Hòa Thuận Tây" },
    { value: "Nam Dương", label: "Nam Dương" },
    { value: "Phước Ninh", label: "Phước Ninh" },
  ],
  "Thanh Khê": [
    { value: "Tam Thuận", label: "Tam Thuận" },
    { value: "Thanh Khê Đông", label: "Thanh Khê Đông" },
    { value: "Thanh Khê Tây", label: "Thanh Khê Tây" },
    { value: "Xuân Hà", label: "Xuân Hà" },
    { value: "Tân Chính", label: "Tân Chính" },
    { value: "Chính Gián", label: "Chính Gián" },
    { value: "Vĩnh Trung", label: "Vĩnh Trung" },
    { value: "Thạc Gián", label: "Thạc Gián" },
    { value: "An Khê", label: "An Khê" },
    { value: "Hòa Khê", label: "Hòa Khê" },
  ],
  "Sơn Trà": [
    { value: "An Hải Bắc", label: "An Hải Bắc" },
    { value: "An Hải Đông", label: "An Hải Đông" },
    { value: "An Hải Tây", label: "An Hải Tây" },
    { value: "Mân Thái", label: "Mân Thái" },
    { value: "Nại Hiên Đông", label: "Nại Hiên Đông" },
    { value: "Phước Mỹ", label: "Phước Mỹ" },
    { value: "Thọ Quang", label: "Thọ Quang" },
  ],
  "Ngũ Hành Sơn": [
    { value: "Hòa Hải", label: "Hòa Hải" },
    { value: "Hòa Quý", label: "Hòa Quý" },
    { value: "Khuê Mỹ", label: "Khuê Mỹ" },
    { value: "Mỹ An", label: "Mỹ An" },
  ],
  "Liên Chiểu": [
    { value: "Hòa Hiệp Bắc", label: "Hòa Hiệp Bắc" },
    { value: "Hòa Hiệp Nam", label: "Hòa Hiệp Nam" },
    { value: "Hòa Khánh Bắc", label: "Hòa Khánh Bắc" },
    { value: "Hòa Khánh Nam", label: "Hòa Khánh Nam" },
    { value: "Hòa Minh", label: "Hòa Minh" },
  ],
  "Cẩm Lệ": [
    { value: "Hòa An", label: "Hòa An" },
    { value: "Hòa Phát", label: "Hòa Phát" },
    { value: "Hòa Thọ Đông", label: "Hòa Thọ Đông" },
    { value: "Hòa Thọ Tây", label: "Hòa Thọ Tây" },
    { value: "Hòa Xuân", label: "Hòa Xuân" },
    { value: "Khuê Trung", label: "Khuê Trung" },
  ],
  "Hòa Vang": [
    { value: "Hòa Bắc", label: "Hòa Bắc" },
    { value: "Hòa Châu", label: "Hòa Châu" },
    { value: "Hòa Khương", label: "Hòa Khương" },
    { value: "Hòa Liên", label: "Hòa Liên" },
    { value: "Hòa Nhơn", label: "Hòa Nhơn" },
    { value: "Hòa Ninh", label: "Hòa Ninh" },
    { value: "Hòa Phong", label: "Hòa Phong" },
    { value: "Hòa Phú", label: "Hòa Phú" },
    { value: "Hòa Phước", label: "Hòa Phước" },
    { value: "Hòa Sơn", label: "Hòa Sơn" },
    { value: "Hòa Tiến", label: "Hòa Tiến" },
  ],
  "Hoàng Sa": [{ value: "Hoàng Sa", label: "Hoàng Sa" }],

  // ===== HÀ NỘI =====
  "Ba Đình": [
    { value: "Phúc Xá", label: "Phúc Xá" },
    { value: "Trúc Bạch", label: "Trúc Bạch" },
    { value: "Vĩnh Phúc", label: "Vĩnh Phúc" },
    { value: "Cống Vị", label: "Cống Vị" },
    { value: "Liễu Giai", label: "Liễu Giai" },
    { value: "Nguyễn Trung Trực", label: "Nguyễn Trung Trực" },
    { value: "Quán Thánh", label: "Quán Thánh" },
    { value: "Ngọc Hà", label: "Ngọc Hà" },
    { value: "Điện Biên", label: "Điện Biên" },
    { value: "Đội Cấn", label: "Đội Cấn" },
    { value: "Ngọc Khánh", label: "Ngọc Khánh" },
    { value: "Kim Mã", label: "Kim Mã" },
    { value: "Giảng Võ", label: "Giảng Võ" },
    { value: "Thành Công", label: "Thành Công" },
  ],
  "Hoàn Kiếm": [
    { value: "Phúc Tân", label: "Phúc Tân" },
    { value: "Đồng Xuân", label: "Đồng Xuân" },
    { value: "Hàng Mã", label: "Hàng Mã" },
    { value: "Hàng Buồm", label: "Hàng Buồm" },
    { value: "Hàng Đào", label: "Hàng Đào" },
    { value: "Hàng Bồ", label: "Hàng Bồ" },
    { value: "Cửa Đông", label: "Cửa Đông" },
    { value: "Lý Thái Tổ", label: "Lý Thái Tổ" },
    { value: "Hàng Bạc", label: "Hàng Bạc" },
    { value: "Hàng Gai", label: "Hàng Gai" },
    { value: "Chương Dương", label: "Chương Dương" },
    { value: "Hàng Trống", label: "Hàng Trống" },
    { value: "Cửa Nam", label: "Cửa Nam" },
    { value: "Hàng Bông", label: "Hàng Bông" },
    { value: "Tràng Tiền", label: "Tràng Tiền" },
    { value: "Trần Hưng Đạo", label: "Trần Hưng Đạo" },
    { value: "Phan Chu Trinh", label: "Phan Chu Trinh" },
    { value: "Hàng Bài", label: "Hàng Bài" },
  ],
  "Tây Hồ": [
    { value: "Bưởi", label: "Bưởi" },
    { value: "Nhật Tân", label: "Nhật Tân" },
    { value: "Phú Thượng", label: "Phú Thượng" },
    { value: "Quảng An", label: "Quảng An" },
    { value: "Thụy Khuê", label: "Thụy Khuê" },
    { value: "Tứ Liên", label: "Tứ Liên" },
    { value: "Xuân La", label: "Xuân La" },
    { value: "Yên Phụ", label: "Yên Phụ" },
  ],
  "Long Biên": [
    { value: "Bồ Đề", label: "Bồ Đề" },
    { value: "Cự Khối", label: "Cự Khối" },
    { value: "Đức Giang", label: "Đức Giang" },
    { value: "Gia Thụy", label: "Gia Thụy" },
    { value: "Giang Biên", label: "Giang Biên" },
    { value: "Long Biên", label: "Long Biên" },
    { value: "Ngọc Lâm", label: "Ngọc Lâm" },
    { value: "Ngọc Thụy", label: "Ngọc Thụy" },
    { value: "Phúc Đồng", label: "Phúc Đồng" },
    { value: "Phúc Lợi", label: "Phúc Lợi" },
    { value: "Sài Đồng", label: "Sài Đồng" },
    { value: "Thạch Bàn", label: "Thạch Bàn" },
    { value: "Thượng Thanh", label: "Thượng Thanh" },
    { value: "Việt Hưng", label: "Việt Hưng" },
  ],
  "Cầu Giấy": [
    { value: "Dịch Vọng", label: "Dịch Vọng" },
    { value: "Dịch Vọng Hậu", label: "Dịch Vọng Hậu" },
    { value: "Mai Dịch", label: "Mai Dịch" },
    { value: "Nghĩa Đô", label: "Nghĩa Đô" },
    { value: "Nghĩa Tân", label: "Nghĩa Tân" },
    { value: "Quan Hoa", label: "Quan Hoa" },
    { value: "Trung Hòa", label: "Trung Hòa" },
    { value: "Yên Hòa", label: "Yên Hòa" },
  ],
  "Đống Đa": [
    { value: "Cát Linh", label: "Cát Linh" },
    { value: "Hàng Bột", label: "Hàng Bột" },
    { value: "Khâm Thiên", label: "Khâm Thiên" },
    { value: "Khương Thượng", label: "Khương Thượng" },
    { value: "Kim Liên", label: "Kim Liên" },
    { value: "Láng Hạ", label: "Láng Hạ" },
    { value: "Láng Thượng", label: "Láng Thượng" },
    { value: "Nam Đồng", label: "Nam Đồng" },
    { value: "Ngã Tư Sở", label: "Ngã Tư Sở" },
    { value: "Ô Chợ Dừa", label: "Ô Chợ Dừa" },
    { value: "Phương Liên", label: "Phương Liên" },
    { value: "Phương Mai", label: "Phương Mai" },
    { value: "Quang Trung", label: "Quang Trung" },
    { value: "Quốc Tử Giám", label: "Quốc Tử Giám" },
    { value: "Thịnh Quang", label: "Thịnh Quang" },
    { value: "Thổ Quan", label: "Thổ Quan" },
    { value: "Trung Liệt", label: "Trung Liệt" },
    { value: "Trung Phụng", label: "Trung Phụng" },
    { value: "Trung Tự", label: "Trung Tự" },
    { value: "Văn Chương", label: "Văn Chương" },
    { value: "Văn Miếu", label: "Văn Miếu" },
  ],
  "Hai Bà Trưng": [
    { value: "Bạch Đằng", label: "Bạch Đằng" },
    { value: "Bạch Mai", label: "Bạch Mai" },
    { value: "Bùi Thị Xuân", label: "Bùi Thị Xuân" },
    { value: "Cầu Dền", label: "Cầu Dền" },
    { value: "Đống Mác", label: "Đống Mác" },
    { value: "Đồng Nhân", label: "Đồng Nhân" },
    { value: "Đồng Tâm", label: "Đồng Tâm" },
    { value: "Lê Đại Hành", label: "Lê Đại Hành" },
    { value: "Minh Khai", label: "Minh Khai" },
    { value: "Ngô Thì Nhậm", label: "Ngô Thì Nhậm" },
    { value: "Nguyễn Du", label: "Nguyễn Du" },
    { value: "Phạm Đình Hổ", label: "Phạm Đình Hổ" },
    { value: "Phố Huế", label: "Phố Huế" },
    { value: "Quỳnh Lôi", label: "Quỳnh Lôi" },
    { value: "Quỳnh Mai", label: "Quỳnh Mai" },
    { value: "Thanh Lương", label: "Thanh Lương" },
    { value: "Thanh Nhàn", label: "Thanh Nhàn" },
    { value: "Trương Định", label: "Trương Định" },
    { value: "Vĩnh Tuy", label: "Vĩnh Tuy" },
  ],
  "Hoàng Mai": [
    { value: "Đại Kim", label: "Đại Kim" },
    { value: "Định Công", label: "Định Công" },
    { value: "Giáp Bát", label: "Giáp Bát" },
    { value: "Hoàng Liệt", label: "Hoàng Liệt" },
    { value: "Hoàng Văn Thụ", label: "Hoàng Văn Thụ" },
    { value: "Lĩnh Nam", label: "Lĩnh Nam" },
    { value: "Mai Động", label: "Mai Động" },
    { value: "Tân Mai", label: "Tân Mai" },
    { value: "Thanh Trì", label: "Thanh Trì" },
    { value: "Thịnh Liệt", label: "Thịnh Liệt" },
    { value: "Trần Phú", label: "Trần Phú" },
    { value: "Tương Mai", label: "Tương Mai" },
    { value: "Vĩnh Hưng", label: "Vĩnh Hưng" },
    { value: "Yên Sở", label: "Yên Sở" },
  ],
  "Thanh Xuân": [
    { value: "Hạ Đình", label: "Hạ Đình" },
    { value: "Khương Đình", label: "Khương Đình" },
    { value: "Khương Mai", label: "Khương Mai" },
    { value: "Khương Trung", label: "Khương Trung" },
    { value: "Kim Giang", label: "Kim Giang" },
    { value: "Nhân Chính", label: "Nhân Chính" },
    { value: "Phương Liệt", label: "Phương Liệt" },
    { value: "Thanh Xuân Bắc", label: "Thanh Xuân Bắc" },
    { value: "Thanh Xuân Nam", label: "Thanh Xuân Nam" },
    { value: "Thanh Xuân Trung", label: "Thanh Xuân Trung" },
    { value: "Thượng Đình", label: "Thượng Đình" },
  ],
  "Sóc Sơn": [
    { value: "Bắc Phú", label: "Bắc Phú" },
    { value: "Bắc Sơn", label: "Bắc Sơn" },
    { value: "Đông Xuân", label: "Đông Xuân" },
    { value: "Đức Hòa", label: "Đức Hòa" },
    { value: "Hiền Ninh", label: "Hiền Ninh" },
    { value: "Hồng Kỳ", label: "Hồng Kỳ" },
    { value: "Kim Lũ", label: "Kim Lũ" },
    { value: "Mai Đình", label: "Mai Đình" },
    { value: "Minh Phú", label: "Minh Phú" },
    { value: "Minh Trí", label: "Minh Trí" },
    { value: "Nam Sơn", label: "Nam Sơn" },
    { value: "Phú Cường", label: "Phú Cường" },
    { value: "Phú Minh", label: "Phú Minh" },
    { value: "Phù Linh", label: "Phù Linh" },
    { value: "Phù Lỗ", label: "Phù Lỗ" },
    { value: "Quang Tiến", label: "Quang Tiến" },
    { value: "Sóc Sơn", label: "Sóc Sơn" },
    { value: "Tân Dân", label: "Tân Dân" },
    { value: "Tân Hưng", label: "Tân Hưng" },
    { value: "Tân Minh", label: "Tân Minh" },
    { value: "Thanh Xuân", label: "Thanh Xuân" },
    { value: "Tiên Dược", label: "Tiên Dược" },
    { value: "Trung Giã", label: "Trung Giã" },
    { value: "Việt Long", label: "Việt Long" },
    { value: "Xuân Giang", label: "Xuân Giang" },
    { value: "Xuân Thu", label: "Xuân Thu" },
  ],
  "Đông Anh": [
    { value: "Bắc Hồng", label: "Bắc Hồng" },
    { value: "Cổ Loa", label: "Cổ Loa" },
    { value: "Đại Mạch", label: "Đại Mạch" },
    { value: "Đông Anh", label: "Đông Anh" },
    { value: "Đông Hội", label: "Đông Hội" },
    { value: "Dục Tú", label: "Dục Tú" },
    { value: "Hải Bối", label: "Hải Bối" },
    { value: "Kim Chung", label: "Kim Chung" },
    { value: "Kim Nỗ", label: "Kim Nỗ" },
    { value: "Liên Hà", label: "Liên Hà" },
    { value: "Mai Lâm", label: "Mai Lâm" },
    { value: "Nam Hồng", label: "Nam Hồng" },
    { value: "Nguyên Khê", label: "Nguyên Khê" },
    { value: "Tàm Xá", label: "Tàm Xá" },
    { value: "Thụy Lâm", label: "Thụy Lâm" },
    { value: "Tiên Dương", label: "Tiên Dương" },
    { value: "Uy Nỗ", label: "Uy Nỗ" },
    { value: "Vân Hà", label: "Vân Hà" },
    { value: "Vân Nội", label: "Vân Nội" },
    { value: "Việt Hùng", label: "Việt Hùng" },
    { value: "Vĩnh Ngọc", label: "Vĩnh Ngọc" },
    { value: "Võng La", label: "Võng La" },
    { value: "Xuân Canh", label: "Xuân Canh" },
    { value: "Xuân Nộn", label: "Xuân Nộn" },
  ],
  "Gia Lâm": [
    { value: "Bát Tràng", label: "Bát Tràng" },
    { value: "Cổ Bi", label: "Cổ Bi" },
    { value: "Đa Tốn", label: "Đa Tốn" },
    { value: "Đặng Xá", label: "Đặng Xá" },
    { value: "Đình Xuyên", label: "Đình Xuyên" },
    { value: "Đông Dư", label: "Đông Dư" },
    { value: "Dương Hà", label: "Dương Hà" },
    { value: "Dương Quang", label: "Dương Quang" },
    { value: "Dương Xá", label: "Dương Xá" },
    { value: "Kiêu Kỵ", label: "Kiêu Kỵ" },
    { value: "Kim Lan", label: "Kim Lan" },
    { value: "Kim Sơn", label: "Kim Sơn" },
    { value: "Lệ Chi", label: "Lệ Chi" },
    { value: "Ninh Hiệp", label: "Ninh Hiệp" },
    { value: "Phù Đổng", label: "Phù Đổng" },
    { value: "Phú Thị", label: "Phú Thị" },
    { value: "Trâu Quỳ", label: "Trâu Quỳ" },
    { value: "Trung Mầu", label: "Trung Mầu" },
    { value: "Văn Đức", label: "Văn Đức" },
    { value: "Yên Thường", label: "Yên Thường" },
    { value: "Yên Viên", label: "Yên Viên" },
  ],
  "Nam Từ Liêm": [
    { value: "Cầu Diễn", label: "Cầu Diễn" },
    { value: "Đại Mỗ", label: "Đại Mỗ" },
    { value: "Mễ Trì", label: "Mễ Trì" },
    { value: "Mỹ Đình 1", label: "Mỹ Đình 1" },
    { value: "Mỹ Đình 2", label: "Mỹ Đình 2" },
    { value: "Phú Đô", label: "Phú Đô" },
    { value: "Phương Canh", label: "Phương Canh" },
    { value: "Tây Mỗ", label: "Tây Mỗ" },
    { value: "Trung Văn", label: "Trung Văn" },
    { value: "Xuân Phương", label: "Xuân Phương" },
  ],
  "Bắc Từ Liêm": [
    { value: "Cổ Nhuế 1", label: "Cổ Nhuế 1" },
    { value: "Cổ Nhuế 2", label: "Cổ Nhuế 2" },
    { value: "Đông Ngạc", label: "Đông Ngạc" },
    { value: "Đức Thắng", label: "Đức Thắng" },
    { value: "Liên Mạc", label: "Liên Mạc" },
    { value: "Minh Khai", label: "Minh Khai" },
    { value: "Phú Diễn", label: "Phú Diễn" },
    { value: "Phúc Diễn", label: "Phúc Diễn" },
    { value: "Tây Tựu", label: "Tây Tựu" },
    { value: "Thượng Cát", label: "Thượng Cát" },
    { value: "Thụy Phương", label: "Thụy Phương" },
    { value: "Xuân Đỉnh", label: "Xuân Đỉnh" },
    { value: "Xuân Tảo", label: "Xuân Tảo" },
  ],
  "Mê Linh": [
    { value: "Chi Đông", label: "Chi Đông" },
    { value: "Chu Phan", label: "Chu Phan" },
    { value: "Đại Thịnh", label: "Đại Thịnh" },
    { value: "Hoàng Kim", label: "Hoàng Kim" },
    { value: "Kim Hoa", label: "Kim Hoa" },
    { value: "Liên Mạc", label: "Liên Mạc" },
    { value: "Mê Linh", label: "Mê Linh" },
    { value: "Quang Minh", label: "Quang Minh" },
    { value: "Tam Đồng", label: "Tam Đồng" },
    { value: "Thạch Đà", label: "Thạch Đà" },
    { value: "Thanh Lâm", label: "Thanh Lâm" },
    { value: "Tiền Phong", label: "Tiền Phong" },
    { value: "Tiến Thắng", label: "Tiến Thắng" },
    { value: "Tráng Việt", label: "Tráng Việt" },
    { value: "Tự Lập", label: "Tự Lập" },
    { value: "Vạn Yên", label: "Vạn Yên" },
    { value: "Văn Khê", label: "Văn Khê" },
    { value: "Việt Hưng", label: "Việt Hưng" },
  ],
  "Hà Đông": [
    { value: "Biên Giang", label: "Biên Giang" },
    { value: "Đồng Mai", label: "Đồng Mai" },
    { value: "Dương Nội", label: "Dương Nội" },
    { value: "Hà Cầu", label: "Hà Cầu" },
    { value: "Kiến Hưng", label: "Kiến Hưng" },
    { value: "La Khê", label: "La Khê" },
    { value: "Mộ Lao", label: "Mộ Lao" },
    { value: "Nguyễn Trãi", label: "Nguyễn Trãi" },
    { value: "Phú La", label: "Phú La" },
    { value: "Phú Lãm", label: "Phú Lãm" },
    { value: "Phú Lương", label: "Phú Lương" },
    { value: "Quang Trung", label: "Quang Trung" },
    { value: "Vạn Phúc", label: "Vạn Phúc" },
    { value: "Văn Quán", label: "Văn Quán" },
    { value: "Yên Nghĩa", label: "Yên Nghĩa" },
    { value: "Yết Kiêu", label: "Yết Kiêu" },
  ],
  "Sơn Tây": [
    { value: "Lê Lợi", label: "Lê Lợi" },
    { value: "Ngô Quyền", label: "Ngô Quyền" },
    { value: "Phú Thịnh", label: "Phú Thịnh" },
    { value: "Quang Trung", label: "Quang Trung" },
    { value: "Sơn Lộc", label: "Sơn Lộc" },
    { value: "Trung Hưng", label: "Trung Hưng" },
    { value: "Trung Sơn Trầm", label: "Trung Sơn Trầm" },
    { value: "Viên Sơn", label: "Viên Sơn" },
    { value: "Xuân Khanh", label: "Xuân Khanh" },
    { value: "Xuân Sơn", label: "Xuân Sơn" },
    { value: "Cổ Đông", label: "Cổ Đông" },
    { value: "Đường Lâm", label: "Đường Lâm" },
    { value: "Kim Sơn", label: "Kim Sơn" },
    { value: "Thanh Mỹ", label: "Thanh Mỹ" },
  ],
  "Ba Vì": [
    { value: "Ba Trại", label: "Ba Trại" },
    { value: "Ba Vì", label: "Ba Vì" },
    { value: "Cẩm Lĩnh", label: "Cẩm Lĩnh" },
    { value: "Châu Sơn", label: "Châu Sơn" },
    { value: "Chu Minh", label: "Chu Minh" },
    { value: "Cổ Đô", label: "Cổ Đô" },
    { value: "Đông Quang", label: "Đông Quang" },
    { value: "Đồng Thái", label: "Đồng Thái" },
    { value: "Khánh Thượng", label: "Khánh Thượng" },
    { value: "Minh Châu", label: "Minh Châu" },
    { value: "Minh Quang", label: "Minh Quang" },
    { value: "Phong Vân", label: "Phong Vân" },
    { value: "Phú Châu", label: "Phú Châu" },
    { value: "Phú Cường", label: "Phú Cường" },
    { value: "Phú Đông", label: "Phú Đông" },
    { value: "Phú Phương", label: "Phú Phương" },
    { value: "Phú Sơn", label: "Phú Sơn" },
    { value: "Sơn Đà", label: "Sơn Đà" },
    { value: "Tản Hồng", label: "Tản Hồng" },
    { value: "Tản Lĩnh", label: "Tản Lĩnh" },
    { value: "Thái Hòa", label: "Thái Hòa" },
    { value: "Thuần Mỹ", label: "Thuần Mỹ" },
    { value: "Thụy An", label: "Thụy An" },
    { value: "Tiên Phong", label: "Tiên Phong" },
    { value: "Tòng Bạt", label: "Tòng Bạt" },
    { value: "Vân Hòa", label: "Vân Hòa" },
    { value: "Vạn Thắng", label: "Vạn Thắng" },
    { value: "Vật Lại", label: "Vật Lại" },
    { value: "Yên Bài", label: "Yên Bài" },
  ],
  "Phúc Thọ": [
    { value: "Hát Môn", label: "Hát Môn" },
    { value: "Hiệp Thuận", label: "Hiệp Thuận" },
    { value: "Liên Hiệp", label: "Liên Hiệp" },
    { value: "Long Xuyên", label: "Long Xuyên" },
    { value: "Ngọc Tảo", label: "Ngọc Tảo" },
    { value: "Phúc Hòa", label: "Phúc Hòa" },
    { value: "Phụng Thượng", label: "Phụng Thượng" },
    { value: "Phương Độ", label: "Phương Độ" },
    { value: "Sen Chiểu", label: "Sen Chiểu" },
    { value: "Tam Hiệp", label: "Tam Hiệp" },
    { value: "Tam Thuấn", label: "Tam Thuấn" },
    { value: "Thanh Đa", label: "Thanh Đa" },
    { value: "Thọ Lộc", label: "Thọ Lộc" },
    { value: "Thượng Cốc", label: "Thượng Cốc" },
    { value: "Tích Giang", label: "Tích Giang" },
    { value: "Trạch Mỹ Lộc", label: "Trạch Mỹ Lộc" },
    { value: "Vân Hà", label: "Vân Hà" },
    { value: "Vân Nam", label: "Vân Nam" },
    { value: "Vân Phúc", label: "Vân Phúc" },
    { value: "Võng Xuyên", label: "Võng Xuyên" },
    { value: "Xuân Phú", label: "Xuân Phú" },
    { value: "Phúc Thọ", label: "Phúc Thọ" },
  ],
  "Đan Phượng": [
    { value: "Đan Phượng", label: "Đan Phượng" },
    { value: "Đồng Tháp", label: "Đồng Tháp" },
    { value: "Hạ Mỗ", label: "Hạ Mỗ" },
    { value: "Hồng Hà", label: "Hồng Hà" },
    { value: "Liên Hà", label: "Liên Hà" },
    { value: "Liên Hồng", label: "Liên Hồng" },
    { value: "Liên Trung", label: "Liên Trung" },
    { value: "Phương Đình", label: "Phương Đình" },
    { value: "Song Phượng", label: "Song Phượng" },
    { value: "Tân Hội", label: "Tân Hội" },
    { value: "Tân Lập", label: "Tân Lập" },
    { value: "Thọ An", label: "Thọ An" },
    { value: "Thọ Xuân", label: "Thọ Xuân" },
    { value: "Trung Châu", label: "Trung Châu" },
  ],
  "Hoài Đức": [
    { value: "An Khánh", label: "An Khánh" },
    { value: "An Thượng", label: "An Thượng" },
    { value: "Cát Quế", label: "Cát Quế" },
    { value: "Đắc Sở", label: "Đắc Sở" },
    { value: "Di Trạch", label: "Di Trạch" },
    { value: "Đông La", label: "Đông La" },
    { value: "Đức Giang", label: "Đức Giang" },
    { value: "Đức Thượng", label: "Đức Thượng" },
    { value: "Dương Liễu", label: "Dương Liễu" },
    { value: "Kim Chung", label: "Kim Chung" },
    { value: "La Phù", label: "La Phù" },
    { value: "Lại Yên", label: "Lại Yên" },
    { value: "Minh Khai", label: "Minh Khai" },
    { value: "Sơn Đồng", label: "Sơn Đồng" },
    { value: "Song Phương", label: "Song Phương" },
    { value: "Tiền Yên", label: "Tiền Yên" },
    { value: "Trạm Trôi", label: "Trạm Trôi" },
    { value: "Vân Canh", label: "Vân Canh" },
    { value: "Vân Côn", label: "Vân Côn" },
    { value: "Yên Sở", label: "Yên Sở" },
  ],
  "Quốc Oai": [
    { value: "Cấn Hữu", label: "Cấn Hữu" },
    { value: "Cộng Hòa", label: "Cộng Hòa" },
    { value: "Đại Thành", label: "Đại Thành" },
    { value: "Đồng Quang", label: "Đồng Quang" },
    { value: "Đông Xuân", label: "Đông Xuân" },
    { value: "Đông Yên", label: "Đông Yên" },
    { value: "Hòa Thạch", label: "Hòa Thạch" },
    { value: "Liệp Tuyết", label: "Liệp Tuyết" },
    { value: "Nghĩa Hương", label: "Nghĩa Hương" },
    { value: "Ngọc Liệp", label: "Ngọc Liệp" },
    { value: "Ngọc Mỹ", label: "Ngọc Mỹ" },
    { value: "Phú Cát", label: "Phú Cát" },
    { value: "Phú Mãn", label: "Phú Mãn" },
    { value: "Phượng Cách", label: "Phượng Cách" },
    { value: "Quốc Oai", label: "Quốc Oai" },
    { value: "Sài Sơn", label: "Sài Sơn" },
    { value: "Tân Hòa", label: "Tân Hòa" },
    { value: "Tân Phú", label: "Tân Phú" },
    { value: "Thạch Thán", label: "Thạch Thán" },
    { value: "Tuyết Nghĩa", label: "Tuyết Nghĩa" },
    { value: "Yên Sơn", label: "Yên Sơn" },
  ],
  "Thạch Thất": [
    { value: "Bình Phú", label: "Bình Phú" },
    { value: "Bình Yên", label: "Bình Yên" },
    { value: "Cẩm Yên", label: "Cẩm Yên" },
    { value: "Cần Kiệm", label: "Cần Kiệm" },
    { value: "Canh Nậu", label: "Canh Nậu" },
    { value: "Chàng Sơn", label: "Chàng Sơn" },
    { value: "Đại Đồng", label: "Đại Đồng" },
    { value: "Dị Nậu", label: "Dị Nậu" },
    { value: "Đồng Trúc", label: "Đồng Trúc" },
    { value: "Hạ Bằng", label: "Hạ Bằng" },
    { value: "Hương Ngải", label: "Hương Ngải" },
    { value: "Hữu Bằng", label: "Hữu Bằng" },
    { value: "Kim Quan", label: "Kim Quan" },
    { value: "Lại Thượng", label: "Lại Thượng" },
    { value: "Liên Quan", label: "Liên Quan" },
    { value: "Phú Kim", label: "Phú Kim" },
    { value: "Phùng Xá", label: "Phùng Xá" },
    { value: "Tân Xã", label: "Tân Xã" },
    { value: "Thạch Hòa", label: "Thạch Hòa" },
    { value: "Thạch Xá", label: "Thạch Xá" },
    { value: "Tiến Xuân", label: "Tiến Xuân" },
    { value: "Yên Bình", label: "Yên Bình" },
    { value: "Yên Trung", label: "Yên Trung" },
  ],
  "Chương Mỹ": [
    { value: "Chúc Sơn", label: "Chúc Sơn" },
    { value: "Xuân Mai", label: "Xuân Mai" },
    { value: "Đại Yên", label: "Đại Yên" },
    { value: "Đồng Lạc", label: "Đồng Lạc" },
    { value: "Đồng Phú", label: "Đồng Phú" },
    { value: "Đông Phương Yên", label: "Đông Phương Yên" },
    { value: "Đông Sơn", label: "Đông Sơn" },
    { value: "Hòa Chính", label: "Hòa Chính" },
    { value: "Hoàng Diệu", label: "Hoàng Diệu" },
    { value: "Hoàng Văn Thụ", label: "Hoàng Văn Thụ" },
    { value: "Hồng Phong", label: "Hồng Phong" },
    { value: "Hợp Đồng", label: "Hợp Đồng" },
    { value: "Hữu Văn", label: "Hữu Văn" },
    { value: "Lam Điền", label: "Lam Điền" },
    { value: "Mỹ Lương", label: "Mỹ Lương" },
    { value: "Nam Phương Tiến", label: "Nam Phương Tiến" },
    { value: "Ngọc Hòa", label: "Ngọc Hòa" },
    { value: "Phú Nam An", label: "Phú Nam An" },
    { value: "Phú Nghĩa", label: "Phú Nghĩa" },
    { value: "Phụng Châu", label: "Phụng Châu" },
    { value: "Quảng Bị", label: "Quảng Bị" },
    { value: "Tân Tiến", label: "Tân Tiến" },
    { value: "Thủy Xuân Tiên", label: "Thủy Xuân Tiên" },
    { value: "Tiên Phương", label: "Tiên Phương" },
    { value: "Tốt Động", label: "Tốt Động" },
    { value: "Trần Phú", label: "Trần Phú" },
    { value: "Trung Hòa", label: "Trung Hòa" },
    { value: "Trường Yên", label: "Trường Yên" },
    { value: "Văn Võ", label: "Văn Võ" },
  ],
  "Thanh Oai": [
    { value: "Bích Hòa", label: "Bích Hòa" },
    { value: "Bình Minh", label: "Bình Minh" },
    { value: "Cao Dương", label: "Cao Dương" },
    { value: "Cao Viên", label: "Cao Viên" },
    { value: "Cự Khê", label: "Cự Khê" },
    { value: "Dân Hòa", label: "Dân Hòa" },
    { value: "Đỗ Động", label: "Đỗ Động" },
    { value: "Hồng Dương", label: "Hồng Dương" },
    { value: "Kim An", label: "Kim An" },
    { value: "Kim Bài", label: "Kim Bài" },
    { value: "Kim Thư", label: "Kim Thư" },
    { value: "Liên Châu", label: "Liên Châu" },
    { value: "Mỹ Hưng", label: "Mỹ Hưng" },
    { value: "Phương Trung", label: "Phương Trung" },
    { value: "Tam Hưng", label: "Tam Hưng" },
    { value: "Tân Ước", label: "Tân Ước" },
    { value: "Thanh Cao", label: "Thanh Cao" },
    { value: "Thanh Mai", label: "Thanh Mai" },
    { value: "Thanh Thùy", label: "Thanh Thùy" },
    { value: "Thanh Văn", label: "Thanh Văn" },
    { value: "Xuân Dương", label: "Xuân Dương" },
  ],
  "Thường Tín": [
    { value: "Chương Dương", label: "Chương Dương" },
    { value: "Dũng Tiến", label: "Dũng Tiến" },
    { value: "Duyên Thái", label: "Duyên Thái" },
    { value: "Hà Hồi", label: "Hà Hồi" },
    { value: "Hiền Giang", label: "Hiền Giang" },
    { value: "Hòa Bình", label: "Hòa Bình" },
    { value: "Khánh Hà", label: "Khánh Hà" },
    { value: "Lê Lợi", label: "Lê Lợi" },
    { value: "Liên Phương", label: "Liên Phương" },
    { value: "Minh Cường", label: "Minh Cường" },
    { value: "Nghiêm Xuyên", label: "Nghiêm Xuyên" },
    { value: "Nguyễn Trãi", label: "Nguyễn Trãi" },
    { value: "Nhị Khê", label: "Nhị Khê" },
    { value: "Ninh Sở", label: "Ninh Sở" },
    { value: "Quất Động", label: "Quất Động" },
    { value: "Tân Minh", label: "Tân Minh" },
    { value: "Thắng Lợi", label: "Thắng Lợi" },
    { value: "Thống Nhất", label: "Thống Nhất" },
    { value: "Thư Phú", label: "Thư Phú" },
    { value: "Thường Tín", label: "Thường Tín" },
    { value: "Tiền Phong", label: "Tiền Phong" },
    { value: "Tô Hiệu", label: "Tô Hiệu" },
    { value: "Tự Nhiên", label: "Tự Nhiên" },
    { value: "Vạn Điểm", label: "Vạn Điểm" },
    { value: "Văn Bình", label: "Văn Bình" },
    { value: "Văn Phú", label: "Văn Phú" },
    { value: "Văn Tự", label: "Văn Tự" },
    { value: "Vân Tảo", label: "Vân Tảo" },
  ],
  "Phú Xuyên": [
    { value: "Bạch Hạ", label: "Bạch Hạ" },
    { value: "Châu Can", label: "Châu Can" },
    { value: "Chuyên Mỹ", label: "Chuyên Mỹ" },
    { value: "Đại Thắng", label: "Đại Thắng" },
    { value: "Đại Xuyên", label: "Đại Xuyên" },
    { value: "Hoàng Long", label: "Hoàng Long" },
    { value: "Hồng Minh", label: "Hồng Minh" },
    { value: "Hồng Thái", label: "Hồng Thái" },
    { value: "Khai Thái", label: "Khai Thái" },
    { value: "Minh Tân", label: "Minh Tân" },
    { value: "Nam Phong", label: "Nam Phong" },
    { value: "Nam Tiến", label: "Nam Tiến" },
    { value: "Nam Triều", label: "Nam Triều" },
    { value: "Phú Túc", label: "Phú Túc" },
    { value: "Phú Xuyên", label: "Phú Xuyên" },
    { value: "Phú Yên", label: "Phú Yên" },
    { value: "Phúc Tiến", label: "Phúc Tiến" },
    { value: "Phượng Dực", label: "Phượng Dực" },
    { value: "Quang Lãng", label: "Quang Lãng" },
    { value: "Quang Trung", label: "Quang Trung" },
    { value: "Sơn Hà", label: "Sơn Hà" },
    { value: "Tân Dân", label: "Tân Dân" },
    { value: "Thụy Phú", label: "Thụy Phú" },
    { value: "Tri Thủy", label: "Tri Thủy" },
    { value: "Tri Trung", label: "Tri Trung" },
    { value: "Văn Hoàng", label: "Văn Hoàng" },
    { value: "Vân Từ", label: "Vân Từ" },
  ],
  "Ứng Hòa": [
    { value: "Cao Thành", label: "Cao Thành" },
    { value: "Đại Cường", label: "Đại Cường" },
    { value: "Đại Hùng", label: "Đại Hùng" },
    { value: "Đội Bình", label: "Đội Bình" },
    { value: "Đông Lỗ", label: "Đông Lỗ" },
    { value: "Đồng Tân", label: "Đồng Tân" },
    { value: "Đồng Tiến", label: "Đồng Tiến" },
    { value: "Hòa Lâm", label: "Hòa Lâm" },
    { value: "Hòa Nam", label: "Hòa Nam" },
    { value: "Hòa Phú", label: "Hòa Phú" },
    { value: "Hòa Xá", label: "Hòa Xá" },
    { value: "Hồng Quang", label: "Hồng Quang" },
    { value: "Kim Đường", label: "Kim Đường" },
    { value: "Liên Bạt", label: "Liên Bạt" },
    { value: "Lưu Hoàng", label: "Lưu Hoàng" },
    { value: "Minh Đức", label: "Minh Đức" },
    { value: "Phù Lưu", label: "Phù Lưu" },
    { value: "Phương Tú", label: "Phương Tú" },
    { value: "Quảng Phú Cầu", label: "Quảng Phú Cầu" },
    { value: "Sơn Công", label: "Sơn Công" },
    { value: "Tảo Dương Văn", label: "Tảo Dương Văn" },
    { value: "Trầm Lộng", label: "Trầm Lộng" },
    { value: "Trung Tú", label: "Trung Tú" },
    { value: "Ứng Hòa", label: "Ứng Hòa" },
    { value: "Vạn Thái", label: "Vạn Thái" },
    { value: "Viên An", label: "Viên An" },
    { value: "Viên Nội", label: "Viên Nội" },
  ],
  "Mỹ Đức": [
    { value: "An Mỹ", label: "An Mỹ" },
    { value: "An Phú", label: "An Phú" },
    { value: "An Tiến", label: "An Tiến" },
    { value: "Bột Xuyên", label: "Bột Xuyên" },
    { value: "Đại Hưng", label: "Đại Hưng" },
    { value: "Đại Nghĩa", label: "Đại Nghĩa" },
    { value: "Đốc Tín", label: "Đốc Tín" },
    { value: "Đồng Tâm", label: "Đồng Tâm" },
    { value: "Hồng Sơn", label: "Hồng Sơn" },
    { value: "Hợp Thanh", label: "Hợp Thanh" },
    { value: "Hợp Tiến", label: "Hợp Tiến" },
    { value: "Hùng Tiến", label: "Hùng Tiến" },
    { value: "Hương Sơn", label: "Hương Sơn" },
    { value: "Lê Thanh", label: "Lê Thanh" },
    { value: "Mỹ Thành", label: "Mỹ Thành" },
    { value: "Phù Lưu Tế", label: "Phù Lưu Tế" },
    { value: "Phúc Lâm", label: "Phúc Lâm" },
    { value: "Phùng Xá", label: "Phùng Xá" },
    { value: "Thượng Lâm", label: "Thượng Lâm" },
    { value: "Tuy Lai", label: "Tuy Lai" },
    { value: "Vạn Kim", label: "Vạn Kim" },
    { value: "Xuy Xá", label: "Xuy Xá" },
  ],

  // ===== HỒ CHÍ MINH =====
  "Quận 1": [
    { value: "Bến Nghé", label: "Bến Nghé" },
    { value: "Bến Thành", label: "Bến Thành" },
    { value: "Cầu Kho", label: "Cầu Kho" },
    { value: "Cầu Ông Lãnh", label: "Cầu Ông Lãnh" },
    { value: "Cô Giang", label: "Cô Giang" },
    { value: "Đa Kao", label: "Đa Kao" },
    { value: "Nguyễn Cư Trinh", label: "Nguyễn Cư Trinh" },
    { value: "Nguyễn Thái Bình", label: "Nguyễn Thái Bình" },
    { value: "Phạm Ngũ Lão", label: "Phạm Ngũ Lão" },
    { value: "Tân Định", label: "Tân Định" },
  ],
  "Quận 3": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
  ],
  "Quận 4": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
    { value: "Phường 15", label: "Phường 15" },
    { value: "Phường 16", label: "Phường 16" },
    { value: "Phường 18", label: "Phường 18" },
  ],
  "Quận 5": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
    { value: "Phường 15", label: "Phường 15" },
  ],
  "Quận 6": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
  ],
  "Quận 7": [
    { value: "Bình Thuận", label: "Bình Thuận" },
    { value: "Phú Mỹ", label: "Phú Mỹ" },
    { value: "Phú Thuận", label: "Phú Thuận" },
    { value: "Tân Hưng", label: "Tân Hưng" },
    { value: "Tân Kiểng", label: "Tân Kiểng" },
    { value: "Tân Phong", label: "Tân Phong" },
    { value: "Tân Phú", label: "Tân Phú" },
    { value: "Tân Quy", label: "Tân Quy" },
    { value: "Tân Thuận Đông", label: "Tân Thuận Đông" },
    { value: "Tân Thuận Tây", label: "Tân Thuận Tây" },
  ],
  "Quận 8": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
    { value: "Phường 15", label: "Phường 15" },
    { value: "Phường 16", label: "Phường 16" },
  ],
  "Quận 10": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
    { value: "Phường 15", label: "Phường 15" },
  ],
  "Quận 11": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
    { value: "Phường 15", label: "Phường 15" },
    { value: "Phường 16", label: "Phường 16" },
  ],
  "Quận 12": [
    { value: "An Phú Đông", label: "An Phú Đông" },
    { value: "Đông Hưng Thuận", label: "Đông Hưng Thuận" },
    { value: "Hiệp Thành", label: "Hiệp Thành" },
    { value: "Tân Chánh Hiệp", label: "Tân Chánh Hiệp" },
    { value: "Tân Hưng Thuận", label: "Tân Hưng Thuận" },
    { value: "Tân Thới Hiệp", label: "Tân Thới Hiệp" },
    { value: "Tân Thới Nhất", label: "Tân Thới Nhất" },
    { value: "Thạnh Lộc", label: "Thạnh Lộc" },
    { value: "Thạnh Xuân", label: "Thạnh Xuân" },
    { value: "Thới An", label: "Thới An" },
    { value: "Trung Mỹ Tây", label: "Trung Mỹ Tây" },
  ],
  "Bình Thạnh": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
    { value: "Phường 15", label: "Phường 15" },
    { value: "Phường 17", label: "Phường 17" },
    { value: "Phường 19", label: "Phường 19" },
    { value: "Phường 21", label: "Phường 21" },
    { value: "Phường 22", label: "Phường 22" },
    { value: "Phường 24", label: "Phường 24" },
    { value: "Phường 25", label: "Phường 25" },
    { value: "Phường 26", label: "Phường 26" },
    { value: "Phường 27", label: "Phường 27" },
    { value: "Phường 28", label: "Phường 28" },
  ],
  "Tân Bình": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
    { value: "Phường 15", label: "Phường 15" },
  ],
  "Tân Phú": [
    { value: "Hiệp Tân", label: "Hiệp Tân" },
    { value: "Hòa Thạnh", label: "Hòa Thạnh" },
    { value: "Phú Thạnh", label: "Phú Thạnh" },
    { value: "Phú Thọ Hòa", label: "Phú Thọ Hòa" },
    { value: "Phú Trung", label: "Phú Trung" },
    { value: "Sơn Kỳ", label: "Sơn Kỳ" },
    { value: "Tân Quý", label: "Tân Quý" },
    { value: "Tân Sơn Nhì", label: "Tân Sơn Nhì" },
    { value: "Tân Thành", label: "Tân Thành" },
    { value: "Tân Thới Hòa", label: "Tân Thới Hòa" },
    { value: "Tây Thạnh", label: "Tây Thạnh" },
  ],
  "Phú Nhuận": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 2", label: "Phường 2" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
    { value: "Phường 15", label: "Phường 15" },
    { value: "Phường 17", label: "Phường 17" },
  ],
  "Gò Vấp": [
    { value: "Phường 1", label: "Phường 1" },
    { value: "Phường 3", label: "Phường 3" },
    { value: "Phường 4", label: "Phường 4" },
    { value: "Phường 5", label: "Phường 5" },
    { value: "Phường 6", label: "Phường 6" },
    { value: "Phường 7", label: "Phường 7" },
    { value: "Phường 8", label: "Phường 8" },
    { value: "Phường 9", label: "Phường 9" },
    { value: "Phường 10", label: "Phường 10" },
    { value: "Phường 11", label: "Phường 11" },
    { value: "Phường 12", label: "Phường 12" },
    { value: "Phường 13", label: "Phường 13" },
    { value: "Phường 14", label: "Phường 14" },
    { value: "Phường 15", label: "Phường 15" },
    { value: "Phường 16", label: "Phường 16" },
    { value: "Phường 17", label: "Phường 17" },
  ],
  "Bình Tân": [
    { value: "An Lạc", label: "An Lạc" },
    { value: "An Lạc A", label: "An Lạc A" },
    { value: "Bình Hưng Hòa", label: "Bình Hưng Hòa" },
    { value: "Bình Hưng Hòa A", label: "Bình Hưng Hòa A" },
    { value: "Bình Hưng Hòa B", label: "Bình Hưng Hòa B" },
    { value: "Bình Trị Đông", label: "Bình Trị Đông" },
    { value: "Bình Trị Đông A", label: "Bình Trị Đông A" },
    { value: "Bình Trị Đông B", label: "Bình Trị Đông B" },
    { value: "Tân Tạo", label: "Tân Tạo" },
    { value: "Tân Tạo A", label: "Tân Tạo A" },
  ],
  "Thủ Đức": [
    { value: "Bình Chiểu", label: "Bình Chiểu" },
    { value: "Bình Thọ", label: "Bình Thọ" },
    { value: "Hiệp Bình Chánh", label: "Hiệp Bình Chánh" },
    { value: "Hiệp Bình Phước", label: "Hiệp Bình Phước" },
    { value: "Linh Chiểu", label: "Linh Chiểu" },
    { value: "Linh Đông", label: "Linh Đông" },
    { value: "Linh Tây", label: "Linh Tây" },
    { value: "Linh Trung", label: "Linh Trung" },
    { value: "Linh Xuân", label: "Linh Xuân" },
    { value: "Tam Bình", label: "Tam Bình" },
    { value: "Tam Phú", label: "Tam Phú" },
    { value: "Trường Thọ", label: "Trường Thọ" },
  ],
  "Củ Chi": [
    { value: "An Nhơn Tây", label: "An Nhơn Tây" },
    { value: "An Phú", label: "An Phú" },
    { value: "An Phú Trung", label: "An Phú Trung" },
    { value: "Bình Mỹ", label: "Bình Mỹ" },
    { value: "Củ Chi", label: "Củ Chi" },
    { value: "Hòa Phú", label: "Hòa Phú" },
    { value: "Nhuận Đức", label: "Nhuận Đức" },
    { value: "Phạm Văn Cội", label: "Phạm Văn Cội" },
    { value: "Phú Hòa Đông", label: "Phú Hòa Đông" },
    { value: "Phú Mỹ Hưng", label: "Phú Mỹ Hưng" },
    { value: "Phước Hiệp", label: "Phước Hiệp" },
    { value: "Phước Thạnh", label: "Phước Thạnh" },
    { value: "Phước Vĩnh An", label: "Phước Vĩnh An" },
    { value: "Tân An Hội", label: "Tân An Hội" },
    { value: "Tân Phú Trung", label: "Tân Phú Trung" },
    { value: "Tân Thạnh Đông", label: "Tân Thạnh Đông" },
    { value: "Tân Thạnh Tây", label: "Tân Thạnh Tây" },
    { value: "Tân Thông Hội", label: "Tân Thông Hội" },
    { value: "Thái Mỹ", label: "Thái Mỹ" },
    { value: "Trung An", label: "Trung An" },
    { value: "Trung Lập Hạ", label: "Trung Lập Hạ" },
    { value: "Trung Lập Thượng", label: "Trung Lập Thượng" },
  ],
  "Hóc Môn": [
    { value: "Bà Điểm", label: "Bà Điểm" },
    { value: "Đông Thạnh", label: "Đông Thạnh" },
    { value: "Hóc Môn", label: "Hóc Môn" },
    { value: "Nhị Bình", label: "Nhị Bình" },
    { value: "Tân Hiệp", label: "Tân Hiệp" },
    { value: "Tân Thới Nhì", label: "Tân Thới Nhì" },
    { value: "Tân Xuân", label: "Tân Xuân" },
    { value: "Thới Tam Thôn", label: "Thới Tam Thôn" },
    { value: "Trung Chánh", label: "Trung Chánh" },
    { value: "Xuân Thới Đông", label: "Xuân Thới Đông" },
    { value: "Xuân Thới Sơn", label: "Xuân Thới Sơn" },
    { value: "Xuân Thới Thượng", label: "Xuân Thới Thượng" },
  ],
  "Bình Chánh": [
    { value: "An Phú Tây", label: "An Phú Tây" },
    { value: "Bình Chánh", label: "Bình Chánh" },
    { value: "Bình Hưng", label: "Bình Hưng" },
    { value: "Bình Lợi", label: "Bình Lợi" },
    { value: "Đa Phước", label: "Đa Phước" },
    { value: "Hưng Long", label: "Hưng Long" },
    { value: "Lê Minh Xuân", label: "Lê Minh Xuân" },
    { value: "Phạm Văn Hai", label: "Phạm Văn Hai" },
    { value: "Phong Phú", label: "Phong Phú" },
    { value: "Quy Đức", label: "Quy Đức" },
    { value: "Tân Kiên", label: "Tân Kiên" },
    { value: "Tân Nhựt", label: "Tân Nhựt" },
    { value: "Tân Quý Tây", label: "Tân Quý Tây" },
    { value: "Tân Túc", label: "Tân Túc" },
    { value: "Vĩnh Lộc A", label: "Vĩnh Lộc A" },
    { value: "Vĩnh Lộc B", label: "Vĩnh Lộc B" },
  ],
  "Nhà Bè": [
    { value: "Hiệp Phước", label: "Hiệp Phước" },
    { value: "Long Thới", label: "Long Thới" },
    { value: "Nhà Bè", label: "Nhà Bè" },
    { value: "Nhơn Đức", label: "Nhơn Đức" },
    { value: "Phú Xuân", label: "Phú Xuân" },
    { value: "Phước Kiển", label: "Phước Kiển" },
    { value: "Phước Lộc", label: "Phước Lộc" },
  ],
  "Cần Giờ": [
    { value: "An Thới Đông", label: "An Thới Đông" },
    { value: "Bình Khánh", label: "Bình Khánh" },
    { value: "Cần Thạnh", label: "Cần Thạnh" },
    { value: "Long Hòa", label: "Long Hòa" },
    { value: "Lý Nhơn", label: "Lý Nhơn" },
    { value: "Tam Thôn Hiệp", label: "Tam Thôn Hiệp" },
    { value: "Thạnh An", label: "Thạnh An" },
  ],
}
